In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [7]:
import pandas as pd
import numpy as np

In [11]:
df=pd.read_csv(r"C:\Users\drago\Downloads\archive (1)\sentimentdataset.csv")
df

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! ðŸ’ª ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,728,732,Collaborating on a science project that receiv...,Happy,2017-08-18 18:20:00,ScienceProjectSuccessHighSchool,Facebook,#ScienceFairWinner #HighSchoolScience,20.0,39.0,UK,2017,8,18,18
728,729,733,Attending a surprise birthday party organized ...,Happy,2018-06-22 14:15:00,BirthdayPartyJoyHighSchool,Instagram,#SurpriseCelebration #HighSchoolFriendship,25.0,48.0,USA,2018,6,22,14
729,730,734,Successfully fundraising for a school charity ...,Happy,2019-04-05 17:30:00,CharityFundraisingTriumphHighSchool,Twitter,#CommunityGiving #HighSchoolPhilanthropy,22.0,42.0,Canada,2019,4,5,17
730,731,735,"Participating in a multicultural festival, cel...",Happy,2020-02-29 20:45:00,MulticulturalFestivalJoyHighSchool,Facebook,#CulturalCelebration #HighSchoolUnity,21.0,43.0,UK,2020,2,29,20
731,732,736,Organizing a virtual talent show during challe...,Happy,2020-11-15 15:15:00,VirtualTalentShowSuccessHighSchool,Instagram,#VirtualEntertainment #HighSchoolPositivity,24.0,47.0,USA,2020,11,15,15

In [13]:
df = df.drop(['User','Timestamp','Platform','Country'], axis=1).fillna(0)

In [14]:
df

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Hashtags,Retweets,Likes,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,#Nature #Park,15.0,30.0,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,#Traffic #Morning,5.0,10.0,2023,1,15,8
2,2,2,Just finished an amazing workout! ðŸ’ª ...,Positive,#Fitness #Workout,20.0,40.0,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,#Travel #Adventure,8.0,15.0,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,#Cooking #Food,12.0,25.0,2023,1,15,19
...,...,...,...,...,...,...,...,...,...,...,...
727,728,732,Collaborating on a science project that receiv...,Happy,#ScienceFairWinner #HighSchoolScience,20.0,39.0,2017,8,18,18
728,729,733,Attending a surprise birthday party organized ...,Happy,#SurpriseCelebration #HighSchoolFriendship,25.0,48.0,2018,6,22,14
729,730,734,Successfully fundraising for a school charity ...,Happy,#CommunityGiving #HighSchoolPhilanthropy,22.0,42.0,2019,4,5,17
730,731,735,"Participating in a multicultural festival, cel...",Happy,#CulturalCelebration #HighSchoolUnity,21.0,43.0,2020,2,29,20
731,732,736,Organizing a virtual talent show during challe...,Happy,#VirtualEntertainment #HighSchoolPositivity,24.0,47.0,2020,11,15,15

In [18]:
le = LabelEncoder()
df['Text'] = le.fit_transform(df['Text'])
df

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Hashtags,Retweets,Likes,Year,Month,Day,Hour
0,0,0,105,Positive,#Nature #Park,15.0,30.0,2023,1,15,12
1,1,1,293,Negative,#Traffic #Morning,5.0,10.0,2023,1,15,8
2,2,2,191,Positive,#Fitness #Workout,20.0,40.0,2023,1,15,15
3,3,3,120,Positive,#Travel #Adventure,8.0,15.0,2023,1,15,18
4,4,4,296,Neutral,#Cooking #Food,12.0,25.0,2023,1,15,19
...,...,...,...,...,...,...,...,...,...,...,...
727,728,732,397,Happy,#ScienceFairWinner #HighSchoolScience,20.0,39.0,2017,8,18,18
728,729,733,364,Happy,#SurpriseCelebration #HighSchoolFriendship,25.0,48.0,2018,6,22,14
729,730,734,660,Happy,#CommunityGiving #HighSchoolPhilanthropy,22.0,42.0,2019,4,5,17
730,731,735,596,Happy,#CulturalCelebration #HighSchoolUnity,21.0,43.0,2020,2,29,20
731,732,736,587,Happy,#VirtualEntertainment #HighSchoolPositivity,24.0,47.0,2020,11,15,15

In [19]:
df['Sentiment'] = le.fit_transform(df['Sentiment'])
df

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Hashtags,Retweets,Likes,Year,Month,Day,Hour
0,0,0,105,214,#Nature #Park,15.0,30.0,2023,1,15,12
1,1,1,293,195,#Traffic #Morning,5.0,10.0,2023,1,15,8
2,2,2,191,214,#Fitness #Workout,20.0,40.0,2023,1,15,15
3,3,3,120,214,#Travel #Adventure,8.0,15.0,2023,1,15,18
4,4,4,296,197,#Cooking #Food,12.0,25.0,2023,1,15,19
...,...,...,...,...,...,...,...,...,...,...,...
727,728,732,397,139,#ScienceFairWinner #HighSchoolScience,20.0,39.0,2017,8,18,18
728,729,733,364,139,#SurpriseCelebration #HighSchoolFriendship,25.0,48.0,2018,6,22,14
729,730,734,660,139,#CommunityGiving #HighSchoolPhilanthropy,22.0,42.0,2019,4,5,17
730,731,735,596,139,#CulturalCelebration #HighSchoolUnity,21.0,43.0,2020,2,29,20
731,732,736,587,139,#VirtualEntertainment #HighSchoolPositivity,24.0,47.0,2020,11,15,15

In [28]:
df['Hashtags'] = le.fit_transform(df['Hashtags'])
df

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Hashtags,Retweets,Likes,Year,Month,Day,Hour
0,0,0,105,214,491,15.0,30.0,2023,1,15,12
1,1,1,293,195,674,5.0,10.0,2023,1,15,8
2,2,2,191,214,309,20.0,40.0,2023,1,15,15
3,3,3,120,214,677,8.0,15.0,2023,1,15,18
4,4,4,296,197,158,12.0,25.0,2023,1,15,19
...,...,...,...,...,...,...,...,...,...,...,...
727,728,732,397,139,600,20.0,39.0,2017,8,18,18
728,729,733,364,139,647,25.0,48.0,2018,6,22,14
729,730,734,660,139,128,22.0,42.0,2019,4,5,17
730,731,735,596,139,173,21.0,43.0,2020,2,29,20
731,732,736,587,139,682,24.0,47.0,2020,11,15,15

In [29]:
x=df.drop(['Sentiment'],axis=1)

In [30]:
y=df['Sentiment']

In [31]:
X_train, X_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=42)

In [34]:
model = RandomForestClassifier(random_state=12)

In [35]:
model.fit(X_train, y_train)


y_pred = model.predict(X_val)


accuracy = accuracy_score(y_val, y_pred)
print(f'Model Accuracy: {accuracy*100:.2f}')

Model Accuracy: 40.82

In [36]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical


df_train = pd.read_csv(r"C:\Users\drago\Downloads\archive (1)\sentimentdataset.csv")


df = df.drop(['User','Timestamp','Platform','Country'], axis=1).fillna(0)
le = LabelEncoder()
df['Text'] = le.fit_transform(df['Text'])
df['Sentiment'] = le.fit_transform(df['Sentiment'])
df['Hashtags'] = le.fit_transform(df['Hashtags'])



x=df.drop(['Sentiment'],axis=1)
y=df['Sentiment']

y_encoded = to_categorical(y)

X_train, X_val, y_train, y_val = train_test_split(x, y_encoded, test_size=0.2, random_state=42)

model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(len(le.classes_), activation='softmax'))

model.compile(optimizer=Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=20, batch_size=16, validation_data=(X_val, y_val))

_, accuracy = model.evaluate(X_val, y_val)
print(f'Model Accuracy: {accuracy}')

WARNING:tensorflow:From C:\Users\drago\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

KeyError: "['User', 'Timestamp', 'Platform', 'Country'] not found in axis"

In [40]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from torch.utils.data import DataLoader, TensorDataset
from transformers import BertTokenizer, BertForSequenceClassification
import torch

df = pd.read_csv(r"C:\Users\drago\Downloads\archive (1)\sentimentdataset.csv")

X = df['Text']
y = df['Sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(df['Sentiment'].unique()))

X_train_tokens = tokenizer(list(X_train), padding=True, truncation=True, return_tensors='pt', max_length=128)
y_train_labels = torch.tensor(y_train.map({'Positive': 0, 'Negative': 1, 'Neutral': 2}))  # Map labels to numeric values

X_test_tokens = tokenizer(list(X_test), padding=True, truncation=True, return_tensors='pt', max_length=128)
y_test_labels = torch.tensor(y_test.map({'Positive': 0, 'Negative': 1, 'Neutral': 2}))  # Map labels to numeric values

train_dataset = TensorDataset(X_train_tokens['input_ids'], X_train_tokens['attention_mask'], y_train_labels)
test_dataset = TensorDataset(X_test_tokens['input_ids'], X_test_tokens['attention_mask'], y_test_labels)

train_dataloader = DataLoader(train_dataset, batch_size=4, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=4, shuffle=False)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)
epochs = 3

for epoch in range(epochs):
    model.train()
    total_loss = 0

    for batch in train_dataloader:
        input_ids, attention_mask, labels = batch
        input_ids, attention_mask, labels = input_ids.to(device), attention_mask.to(device), labels.to(device)

        optimizer.zero_grad()

        outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        total_loss += loss.item()

        loss.backward()
        optimizer.step()

    average_loss = total_loss / len(train_dataloader)
    print(f"Epoch {epoch + 1}/{epochs}, Loss: {average_loss}")

# Evaluating BERT model
model.eval()
all_predictions = []
all_labels = []

for batch in test_dataloader:
    input_ids, attention_mask, labels = batch
    input_ids, attention_mask, labels = input_ids.to(device), attention_mask.to(device), labels.to(device)

    with torch.no_grad():
        outputs = model(input_ids, attention_mask=attention_mask)

    logits = outputs.logits
    predictions = torch.argmax(logits, dim=1).cpu().numpy()
    all_predictions.extend(predictions)
    all_labels.extend(labels.cpu().numpy())

# Evaluate the model
accuracy = accuracy_score(all_labels, all_predictions)
print(f'Accuracy: {accuracy:.2f}')
print(classification_report(all_labels, all_predictions))

Downloading vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

OSError: Consistency check failed: file should be of size 440449768 but has size 27813441 (model.safetensors).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.